### ISSUE TITLE
is it possible to output readable keyframe/chunks  data through this parser? 

### ISSUE THREAD

**Issue by daQiuQiu** [AnalyzeOrFeed/aof-file-parser#1]
Hi,
I tried this parser and got binary data for keyframes.
is it possible to output readable keyframe/chunks  data through this parser? 
or how do I convert those binary data?
I'm new to study lol replay data.

Thanks

**Comment by AndreasGassmann** [comment]
Hi, sorry for the late reply.

No, it is not possible to extract readable data from the keyframe and chunks with this package. As far as I know there is no package that does that. You might want to look here for more information: https://github.com/loldevs/leaguespec/wiki
